
services:
  consul:
    image: consul:1.15.4
    container_name: consul
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: "agent -dev -client=0.0.0.0"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://consul:8500/v1/status/leader"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  # rabbitmq:
  #   image: rabbitmq:3-management
  #   container_name: rabbitmq
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   healthcheck:
  #     test: ["CMD", "rabbitmqctl", "status"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #   networks:
  #     - app-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
    networks:
      - app-network

  gateway-service:
    container_name: gateway-service
    build:
      context: .
      dockerfile: ./apps/habits-tracker-gatway/Dockerfile
    ports:
      - "5000:5000"
      
    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - SERVICE_NAME=gateway-service
      - PORT=5000
      - SERVICE_ADDRESS=gateway-service
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - consul
    networks:
      - app-network

  auth-service:
    container_name: auth-service
    build:
      context: .
      dockerfile: ./apps/auth-service/Dockerfile
    ports:
      - "3002:3002"
    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - RABBITMQ_URL=amqp://rabbitmq:5672/
      - PORT=3002
      - SERVICE_ADDRESS=auth-service
    depends_on:
      - consul
      - mongodb
    networks:
      - app-network

  challenges-service:
    container_name: challenges-service
    build:
      context: .
      dockerfile: ./apps/chalenges-service/Dockerfile
    ports:
      - "3003:3003"
    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - RABBITMQ_URL=amqp://rabbitmq:5672/
      - PORT=3003
      - SERVICE_ADDRESS=challenges-service
    depends_on:
      - consul
      - mongodb
    networks:
      - app-network

  habits-service:
    container_name: habits-service
    build:
      context: .
      dockerfile: ./apps/habits-service/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - RABBITMQ_URL=amqp://rabbitmq:5672/
      - PORT=3001
      - SERVICE_ADDRESS=habits-service
    depends_on:
      - consul
      - mongodb
    networks:
      - app-network

  notifications-service:
    container_name: notifications-service 
    build:
      context: .
      dockerfile: ./apps/notifications-service/Dockerfile
    ports:
      - "3006:3006"
    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - RABBITMQ_URL=amqp://rabbitmq:5672/
      - PORT=3003
      - SERVICE_ADDRESS=notifications-service
    depends_on:
      - consul
      - mongodb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: