FROM node:18 AS builder

WORKDIR /usr/src/app

RUN npm install -g pnpm
RUN pnpm config set node-linker=hoisted

COPY pnpm-lock.yaml package.json tsconfig.json ./
RUN pnpm install

COPY . . 
RUN pnpm install --filter=habits-tracker-gateway
RUN pnpm run --filter=habits-tracker-gateway build

FROM node:18

WORKDIR /usr/src/app

RUN npm install -g pnpm

COPY --from=builder /usr/src/app ./ 
COPY --from=builder /usr/src/app/node_modules ./node_modules

WORKDIR /usr/src/app/apps/habits-tracker-gateway

EXPOSE 5000

ENV NODE_ENV=production
ENV PORT=5000
ENV SERVICE_NAME=gateway-service

CMD ["pnpm", "run", "start:dev"]