FROM node:18

WORKDIR /usr/src/app

# Copy lockfile and main configs first
COPY pnpm-lock.yaml package.json tsconfig.json ./

# Install PNPM globally
RUN npm install -g pnpm

# Fix the PNPM symlink issue
RUN pnpm config set node-linker=hoisted

# Install all dependencies
RUN pnpm install

# Copy everything in the monorepo
COPY . .

# Install the dependencies only for the challenges service
RUN pnpm install --filter=challenges-service

# Build the challenges service
RUN pnpm run --filter=challenges-service build

# Expose the port
EXPOSE ${PORT:-3003}

# Environment variables
ENV NODE_ENV=production
ENV CONSUL_HOST=consul
ENV CONSUL_PORT=8500
ENV RABBITMQ_URL=amqp://rabbitmq:5672/
ENV SERVICE_ADDRESS=challenges-service
ENV PORT=3003

# Run the service
CMD ["pnpm", "run", "start:prod"]