FROM node:18

WORKDIR /usr/src/app

COPY pnpm-lock.yaml package.json tsconfig.json ./

RUN npm install -g pnpm

RUN pnpm config set node-linker=hoisted

RUN pnpm install

COPY . .

RUN pnpm install --filter=auth-service

RUN pnpm run --filter=auth-service build

EXPOSE ${PORT:-3002}

ENV NODE_ENV=production
ENV CONSUL_HOST=consul
ENV CONSUL_PORT=8500
ENV RABBITMQ_URL=amqp://rabbitmq:5672/
ENV SERVICE_ADDRESS=auth-service
ENV PORT=3002

CMD ["pnpm", "run", "start:prod"]