name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - 'MYH-25-Implement-habit-progress-tracking-e.g.-marking-habits-as-completed'
  pull_request:
    branches:
      - main
      - 'MYH-25-Implement-habit-progress-tracking-e.g.-marking-habits-as-completed'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          

      - name: Install dependencies
        run: pnpm install 

      # - name: Run ESLint
      #   run: pnpm lint

      - name: Run tests
        run: pnpm test 

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install

      - name: Build the app
        run: pnpm build 

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install

      - name: Build the app
        run: pnpm build

      - name: Deploy to server
        run: echo "🚀 Deploying to production server..." 
